// =====================================================================
// CalculateXY_fixed.v
//
// HAND-WRITTEN reference fix// =====================================================================
// CalculateXYFixed.v
//
// HAND-WRITTEN reference fix for the CalculateXY saturation bug
// (see chat notes / Lidar Documentation.md discussion). This is NOT
// generated by Quartus from a .bdf - it's a copy of the generated
// CalculateXY.v with one clamp added, for simulation only:
//
//   1. Add this file alongside the original CalculateXY design.  This
//      implementation has the unique entity name CalculateXYFixed, so
//      Quartus cannot resolve it to the old CalculateXY BDF macrofunction.
//   2. Run tb_CalculateXY.sv against it - existing vectors (<=2300mm)
//      should still pass with the same results as before.
//   3. Add a couple of out-of-range vectors (e.g. run_vector(0, 6000))
//      and confirm x_pixel/y_pixel now clamp to the screen edge
//      instead of wrapping to a garbage value.
//   4. Once you're happy with it, reproduce the SAME change by hand
//      in CalculateXY.bdf (Quartus Block Editor) if you later want the
//      schematic implementation to contain the same clamp.
//
// -----------------------------------------------------------------
// THE BUG
// -----------------------------------------------------------------
// x_offset/y_offset are a 9-bit two's-complement slice
// (x_lidar[12:4] / y_lidar[12:4], i.e. distance*cos or distance*sin
// divided by 16 for the 16mm/pixel resolution) with NO range check
// before the slice. Anything beyond +-4096mm on a given axis wraps
// around modulo 512 instead of clamping, and since the Y axis only
// has +-240px of headroom before it runs off a 480-tall screen
// (and lidar_data only forwards the low 10 bits of x_pixel/y_pixel,
// so a negative y_pixel aliases too), real LD14P readings (room
// dimensions routinely > 2.3m, its documented/tested max) alias to
// essentially random on-screen pixels.
//
// -----------------------------------------------------------------
// THE FIX
// -----------------------------------------------------------------
// Clamp the RADIUS (raw `distance`, in mm) to MAX_DISTANCE_MM before
// it ever reaches the sin/cos multipliers, instead of clamping each
// axis separately - one clamp protects both, since
// |distance*cos(a)| <= distance and |distance*sin(a)| <= distance.
//
//   MAX_DISTANCE_MM = 239 * 16 = 3824
//     -> x_pixel stays in [81, 559], y_pixel stays in [1, 479],
//        both safely inside the 640x480 frame with margin.
//
// -----------------------------------------------------------------
// WHAT TO DRAW IN THE BDF (CalculateXY.bdf)
// -----------------------------------------------------------------
//   1. ConstantX symbol, size=16, const=3824  -> net "max_distance"
//   2. CMP16 symbol: A = distance (the raw input pin, BEFORE
//      b2v_inst31/late_distance), B = max_distance. Use only the
//      G output ("distance > max_distance") -> net "dist_too_far".
//   3. MPX2_16BIT symbol: S = dist_too_far, E = jedan,
//      I0 = distance, I1 = max_distance -> net "distance_clamped".
//   4. Rewire REG16_LD_CL b2v_inst31's I input from `distance` to
//      `distance_clamped`. Everything downstream is untouched.
// =====================================================================

// PROGRAM		"Quartus II 64-Bit"
// VERSION		"Version 13.1.0 Build 162 10/23/2013 SJ Web Edition"
// CREATED		"Fri Aug 28 12:58:58 2026"
// FIXED (by hand)	"see header above"

module CalculateXYFixed(
	clk,
	angle,
	distance,
	x_pixel,
	y_pixel
);


input wire	clk;
input wire	[15:0] angle;
input wire	[15:0] distance;
output wire	[15:0] x_pixel;
output wire	[15:0] y_pixel;

wire	[31:0] a;
wire	[31:0] b;
wire	[31:0] c;
wire	[15:0] cos;
wire	cos_neg;
wire	[15:0] cosinus;
wire	[31:0] d;
wire	jedan;
wire	[15:0] late_distance;
wire	nq1;
wire	nq2;
wire	nula;
wire	[9:0] nule_10;
wire	[10:0] nule_11;
wire	[12:0] nule_13;
wire	[14:0] nule_15;
wire	[15:0] nule_16;
wire	[19:0] nule_20;
wire	[2:0] nule_3;
wire	[3:0] nule_4;
wire	[4:0] nule_5;
wire	[5:0] nule_6;
wire	[7:0] nule_8;
wire	q1;
wire	q2;
wire	q3;
wire	q4;
wire	[15:0] reference_angle;
wire	[31:0] res;
wire	[15:0] rom_address;
wire	[15:0] rom_cos_addr;
wire	[31:0] rom_sin_addr;
wire	[1:0] sel;
wire	[15:0] sin;
wire	sin_neg;
wire	[15:0] sinus;
wire	[32:0] x_lidar;
wire	[8:0] x_offset;
wire	[32:0] x_temp;
wire	[6:0] xVisi_7;
wire	[32:0] y_lidar;
wire	[8:0] y_offset;
wire	[32:0] y_temp;
wire	[6:0] yVisi_7;
wire	[15:0] SYNTHESIZED_WIRE_0;
wire	SYNTHESIZED_WIRE_1;
wire	SYNTHESIZED_WIRE_2;
wire	SYNTHESIZED_WIRE_3;
wire	[15:0] SYNTHESIZED_WIRE_4;
wire	[15:0] SYNTHESIZED_WIRE_5;
wire	[15:0] SYNTHESIZED_WIRE_6;
wire	[15:0] SYNTHESIZED_WIRE_7;
wire	[15:0] SYNTHESIZED_WIRE_8;
wire	[15:0] SYNTHESIZED_WIRE_9;
wire	SYNTHESIZED_WIRE_10;
wire	SYNTHESIZED_WIRE_11;
wire	[15:0] SYNTHESIZED_WIRE_27;
wire	[15:0] SYNTHESIZED_WIRE_13;
wire	[31:0] SYNTHESIZED_WIRE_14;
wire	[31:0] SYNTHESIZED_WIRE_15;
wire	SYNTHESIZED_WIRE_16;
wire	[15:0] SYNTHESIZED_WIRE_18;
wire	[15:0] SYNTHESIZED_WIRE_19;
wire	[15:0] SYNTHESIZED_WIRE_20;
wire	SYNTHESIZED_WIRE_21;
wire	[15:0] SYNTHESIZED_WIRE_22;
wire	[15:0] SYNTHESIZED_WIRE_23;
wire	SYNTHESIZED_WIRE_24;
wire	SYNTHESIZED_WIRE_25;
wire	[15:0] SYNTHESIZED_WIRE_26;

wire	[31:0] GDFX_TEMP_SIGNAL_3;
wire	[31:0] GDFX_TEMP_SIGNAL_2;
wire	[31:0] GDFX_TEMP_SIGNAL_1;
wire	[31:0] GDFX_TEMP_SIGNAL_0;
wire	[31:0] GDFX_TEMP_SIGNAL_4;
wire	[16:0] GDFX_TEMP_SIGNAL_12;
wire	[16:0] GDFX_TEMP_SIGNAL_13;
wire	[15:0] GDFX_TEMP_SIGNAL_11;
wire	[6:0] GDFX_TEMP_SIGNAL_6;
wire	[6:0] GDFX_TEMP_SIGNAL_5;
wire	[15:0] GDFX_TEMP_SIGNAL_10;
wire	[32:0] GDFX_TEMP_SIGNAL_9;
wire	[32:0] GDFX_TEMP_SIGNAL_8;
wire	[31:0] GDFX_TEMP_SIGNAL_7;

// ---- NEW: distance saturation (see header comment) ----
wire	[15:0] max_distance;
wire	dist_too_far;
wire	[15:0] distance_clamped;


assign	GDFX_TEMP_SIGNAL_3 = {nule_11[10:0],reference_angle[15:0],nule_5[4:0]};
assign	GDFX_TEMP_SIGNAL_2 = {nule_8[7:0],reference_angle[15:0],nule_8[7:0]};
assign	GDFX_TEMP_SIGNAL_1 = {nule_6[5:0],reference_angle[15:0],nule_10[9:0]};
assign	GDFX_TEMP_SIGNAL_0 = {nule_3[2:0],reference_angle[15:0],nule_13[12:0]};
assign	GDFX_TEMP_SIGNAL_4 = {nule_16[15:0],reference_angle[15:0]};
assign	GDFX_TEMP_SIGNAL_12 = {nula,late_distance[15:0]};
assign	GDFX_TEMP_SIGNAL_13 = {nula,late_distance[15:0]};
assign	GDFX_TEMP_SIGNAL_11 = {yVisi_7[6:0],y_offset[8:0]};
assign	GDFX_TEMP_SIGNAL_6 = {y_offset[8],y_offset[8],y_offset[8],y_offset[8],y_offset[8],y_offset[8],y_offset[8]};
assign	GDFX_TEMP_SIGNAL_5 = {x_offset[8],x_offset[8],x_offset[8],x_offset[8],x_offset[8],x_offset[8],x_offset[8]};
assign	GDFX_TEMP_SIGNAL_10 = {xVisi_7[6:0],x_offset[8:0]};
assign	GDFX_TEMP_SIGNAL_9 = {nule_15[14:0],y_temp[32:15]};
assign	GDFX_TEMP_SIGNAL_8 = {nule_15[14:0],x_temp[32:15]};
assign	GDFX_TEMP_SIGNAL_7 = {nule_20[19:0],res[31:20]};


CMP16	b2v_inst(
	.A(angle),
	.B(SYNTHESIZED_WIRE_0),
	.G(SYNTHESIZED_WIRE_11),
	.E(SYNTHESIZED_WIRE_10)
	);


ConstantX	b2v_inst1(
	.DATA_OUT(SYNTHESIZED_WIRE_0));
	defparam	b2v_inst1.const = 9000;
	defparam	b2v_inst1.size = 16;

assign	q3 = SYNTHESIZED_WIRE_1 & nq2;


SUB32	b2v_inst11(
	.E_0(nula),
	.A(GDFX_TEMP_SIGNAL_0),
	.B(GDFX_TEMP_SIGNAL_1),

	.OUT(a));

assign	q4 = SYNTHESIZED_WIRE_2 | SYNTHESIZED_WIRE_3;


MPX4_16BIT	b2v_inst13(
	.data0x(angle),
	.data1x(SYNTHESIZED_WIRE_4),
	.data2x(SYNTHESIZED_WIRE_5),
	.data3x(SYNTHESIZED_WIRE_6),
	.sel(sel),
	.result(reference_angle));


SUB16	b2v_inst14(
	.E_0(nula),
	.A(SYNTHESIZED_WIRE_7),
	.B(angle),

	.OUT(SYNTHESIZED_WIRE_4));



ConstantX	b2v_inst16(
	.DATA_OUT(SYNTHESIZED_WIRE_7));
	defparam	b2v_inst16.const = 18000;
	defparam	b2v_inst16.size = 16;


SUB16	b2v_inst17(
	.E_0(nula),
	.A(SYNTHESIZED_WIRE_8),
	.B(angle),

	.OUT(SYNTHESIZED_WIRE_6));


ConstantX	b2v_inst18(
	.DATA_OUT(SYNTHESIZED_WIRE_8));
	defparam	b2v_inst18.const = 36000;
	defparam	b2v_inst18.size = 16;


SUB16	b2v_inst19(
	.E_0(nula),
	.A(angle),
	.B(SYNTHESIZED_WIRE_9),

	.OUT(SYNTHESIZED_WIRE_5));

assign	nq1 = SYNTHESIZED_WIRE_10 | SYNTHESIZED_WIRE_11;


ConstantX	b2v_inst20(
	.DATA_OUT(SYNTHESIZED_WIRE_9));
	defparam	b2v_inst20.const = 18000;
	defparam	b2v_inst20.size = 16;

assign	sel[0] = q4 | q2;

assign	sel[1] = q3 | q4;


CMP16	b2v_inst24(
	.A(SYNTHESIZED_WIRE_27),
	.B(rom_sin_addr[15:0]),
	.G(SYNTHESIZED_WIRE_16)

	);


ConstantX	b2v_inst25(
	.DATA_OUT(SYNTHESIZED_WIRE_27));
	defparam	b2v_inst25.const = 63;
	defparam	b2v_inst25.size = 16;

assign	b = GDFX_TEMP_SIGNAL_2;


assign	c = GDFX_TEMP_SIGNAL_3;


assign	d = GDFX_TEMP_SIGNAL_4;


assign	xVisi_7 = GDFX_TEMP_SIGNAL_5;



CMP16	b2v_inst3(
	.A(angle),
	.B(SYNTHESIZED_WIRE_13),
	.G(SYNTHESIZED_WIRE_25),
	.E(SYNTHESIZED_WIRE_24),
	.L(SYNTHESIZED_WIRE_21));

assign	yVisi_7 = GDFX_TEMP_SIGNAL_6;


// ---- NEW: clamp `distance` to +-3824mm before it is latched ----
// (239 * 16mm/px = 3824mm -> keeps x_pixel in [81,559] and
//  y_pixel in [1,479], both safely inside the 640x480 frame)
ConstantX	b2v_inst_maxdist(
	.DATA_OUT(max_distance));
	defparam	b2v_inst_maxdist.const = 3824;
	defparam	b2v_inst_maxdist.size = 16;


CMP16	b2v_inst_distcmp(
	.A(distance),
	.B(max_distance),
	.G(dist_too_far)
	);


MPX2_16BIT	b2v_inst_distclamp(
	.S(dist_too_far),
	.E(jedan),
	.I0(distance),
	.I1(max_distance),
	.D(distance_clamped));


REG16_LD_CL	b2v_inst31(
	.LD(jedan),
	.CL(nula),
	.clk(clk),
	.I(distance_clamped),
	.A(late_distance));

assign	rom_sin_addr = GDFX_TEMP_SIGNAL_7;



ADD32	b2v_inst33(
	.C_0(nula),
	.A(a),
	.B(b),

	.OUT(SYNTHESIZED_WIRE_14));


ADD32	b2v_inst34(
	.C_0(nula),
	.A(c),
	.B(d),

	.OUT(SYNTHESIZED_WIRE_15));


ADD32	b2v_inst35(
	.C_0(nula),
	.A(SYNTHESIZED_WIRE_14),
	.B(SYNTHESIZED_WIRE_15),

	.OUT(res));


ConstantX	b2v_inst36(
	.DATA_OUT(nule_16));
	defparam	b2v_inst36.const = 0;
	defparam	b2v_inst36.size = 16;


ConstantX	b2v_inst37(
	.DATA_OUT(nule_10));
	defparam	b2v_inst37.const = 0;
	defparam	b2v_inst37.size = 10;



ConstantX	b2v_inst39(
	.DATA_OUT(nule_3));
	defparam	b2v_inst39.const = 0;
	defparam	b2v_inst39.size = 3;


ConstantX	b2v_inst4(
	.DATA_OUT(SYNTHESIZED_WIRE_13));
	defparam	b2v_inst4.const = 18000;
	defparam	b2v_inst4.size = 16;


ConstantX	b2v_inst40(
	.DATA_OUT(nule_20));
	defparam	b2v_inst40.const = 0;
	defparam	b2v_inst40.size = 20;


MPX2_16BIT	b2v_inst41(
	.S(SYNTHESIZED_WIRE_16),
	.E(jedan),
	.I0(SYNTHESIZED_WIRE_27),
	.I1(rom_sin_addr[15:0]),
	.D(rom_address));


ConstantX	b2v_inst42(
	.DATA_OUT(SYNTHESIZED_WIRE_18));
	defparam	b2v_inst42.const = 63;
	defparam	b2v_inst42.size = 16;


SUB16	b2v_inst43(
	.E_0(nula),
	.A(SYNTHESIZED_WIRE_18),
	.B(rom_address),

	.OUT(rom_cos_addr));


MPX2_16BIT	b2v_inst44(
	.S(sin_neg),
	.E(jedan),
	.I0(sin),
	.I1(SYNTHESIZED_WIRE_19),
	.D(sinus));


assign	sin_neg = q4 | q3;

assign	cos_neg = q3 | q2;


SUB16	b2v_inst48(
	.E_0(nula),
	.A(nule_16),
	.B(sin),

	.OUT(SYNTHESIZED_WIRE_19));


MPX2_16BIT	b2v_inst49(
	.S(cos_neg),
	.E(jedan),
	.I0(cos),
	.I1(SYNTHESIZED_WIRE_20),
	.D(cosinus));

assign	q2 = SYNTHESIZED_WIRE_21 & nq1;


SUB16	b2v_inst50(
	.E_0(nula),
	.A(nule_16),
	.B(cos),

	.OUT(SYNTHESIZED_WIRE_20));


ConstantX	b2v_inst51(
	.DATA_OUT(nule_13));
	defparam	b2v_inst51.const = 0;
	defparam	b2v_inst51.size = 13;


ConstantX	b2v_inst52(
	.DATA_OUT(nule_6));
	defparam	b2v_inst52.const = 0;
	defparam	b2v_inst52.size = 6;

assign	x_lidar = GDFX_TEMP_SIGNAL_8;


assign	y_lidar = GDFX_TEMP_SIGNAL_9;


assign	x_offset = x_lidar[12:4];


assign	y_offset = y_lidar[12:4];



ADD16	b2v_inst57(
	.C_0(nula),
	.A(SYNTHESIZED_WIRE_22),
	.B(GDFX_TEMP_SIGNAL_10),

	.OUT(x_pixel));


ConstantX	b2v_inst58(
	.DATA_OUT(SYNTHESIZED_WIRE_22));
	defparam	b2v_inst58.const = 320;
	defparam	b2v_inst58.size = 16;


SUB16	b2v_inst59(
	.E_0(nula),
	.A(SYNTHESIZED_WIRE_23),
	.B(GDFX_TEMP_SIGNAL_11),

	.OUT(y_pixel));


ConstantX	b2v_inst60(
	.DATA_OUT(SYNTHESIZED_WIRE_23));
	defparam	b2v_inst60.const = 240;
	defparam	b2v_inst60.size = 16;


ConstantX	b2v_inst61(
	.DATA_OUT(nule_8));
	defparam	b2v_inst61.const = 0;
	defparam	b2v_inst61.size = 8;


ConstantX	b2v_inst62(
	.DATA_OUT(nule_15));
	defparam	b2v_inst62.const = 0;
	defparam	b2v_inst62.size = 15;


ROM_SIN	b2v_inst63(
	.wren(nula),
	.clock(clk),
	.address(rom_address[5:0]),
	.data(nule_16),
	.q(sin));


ROM_SIN	b2v_inst64(
	.wren(nula),
	.clock(clk),
	.address(rom_cos_addr[5:0]),
	.data(nule_16),
	.q(cos));


MUL_32b	b2v_inst65(
	.dataa(GDFX_TEMP_SIGNAL_12),
	.datab(cosinus),
	.result(x_temp));


MUL_32b	b2v_inst66(
	.dataa(GDFX_TEMP_SIGNAL_13),
	.datab(sinus),
	.result(y_temp));


ConstantX	b2v_inst67(
	.DATA_OUT(nule_11));
	defparam	b2v_inst67.const = 0;
	defparam	b2v_inst67.size = 11;


ConstantX	b2v_inst68(
	.DATA_OUT(nule_5));
	defparam	b2v_inst68.const = 0;
	defparam	b2v_inst68.size = 5;

assign	nq2 = SYNTHESIZED_WIRE_24 | SYNTHESIZED_WIRE_25;


CMP16	b2v_inst8(
	.A(angle),
	.B(SYNTHESIZED_WIRE_26),
	.G(SYNTHESIZED_WIRE_3),
	.E(SYNTHESIZED_WIRE_2),
	.L(SYNTHESIZED_WIRE_1));


ConstantX	b2v_inst9(
	.DATA_OUT(SYNTHESIZED_WIRE_26));
	defparam	b2v_inst9.const = 27000;
	defparam	b2v_inst9.size = 16;

assign	jedan = 1;
assign	nula = 0;

endmodule
