// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.

// PROGRAM		"Quartus II 64-Bit"
// VERSION		"Version 13.1.0 Build 162 10/23/2013 SJ Web Edition"
// CREATED		"Mon Jul 20 17:16:51 2026"

module CMP32(
	A,
	B,
	G,
	E,
	L
);


input wire	[31:0] A;
input wire	[31:0] B;
output wire	G;
output wire	E;
output wire	L;

wire	[24:24] E_ALTERA_SYNTHESIZED;
wire	[24:24] G_ALTERA_SYNTHESIZED;
wire	[24:24] L_ALTERA_SYNTHESIZED;
wire	SYNTHESIZED_WIRE_0;
wire	SYNTHESIZED_WIRE_1;
wire	SYNTHESIZED_WIRE_2;
wire	SYNTHESIZED_WIRE_3;
wire	SYNTHESIZED_WIRE_4;
wire	SYNTHESIZED_WIRE_5;
wire	SYNTHESIZED_WIRE_6;
wire	SYNTHESIZED_WIRE_7;
wire	SYNTHESIZED_WIRE_8;
wire	SYNTHESIZED_WIRE_9;
wire	SYNTHESIZED_WIRE_10;
wire	SYNTHESIZED_WIRE_11;
wire	SYNTHESIZED_WIRE_12;
wire	SYNTHESIZED_WIRE_13;
wire	SYNTHESIZED_WIRE_14;
wire	SYNTHESIZED_WIRE_15;
wire	SYNTHESIZED_WIRE_16;
wire	SYNTHESIZED_WIRE_17;
wire	SYNTHESIZED_WIRE_18;
wire	SYNTHESIZED_WIRE_19;
wire	SYNTHESIZED_WIRE_20;
wire	SYNTHESIZED_WIRE_21;
wire	SYNTHESIZED_WIRE_22;
wire	SYNTHESIZED_WIRE_23;
wire	SYNTHESIZED_WIRE_24;
wire	SYNTHESIZED_WIRE_25;
wire	SYNTHESIZED_WIRE_26;
wire	SYNTHESIZED_WIRE_27;
wire	SYNTHESIZED_WIRE_28;
wire	SYNTHESIZED_WIRE_29;
wire	SYNTHESIZED_WIRE_30;
wire	SYNTHESIZED_WIRE_31;
wire	SYNTHESIZED_WIRE_32;
wire	SYNTHESIZED_WIRE_33;
wire	SYNTHESIZED_WIRE_34;
wire	SYNTHESIZED_WIRE_35;
wire	SYNTHESIZED_WIRE_36;
wire	SYNTHESIZED_WIRE_37;
wire	SYNTHESIZED_WIRE_38;
wire	SYNTHESIZED_WIRE_39;
wire	SYNTHESIZED_WIRE_40;
wire	SYNTHESIZED_WIRE_41;
wire	SYNTHESIZED_WIRE_42;
wire	SYNTHESIZED_WIRE_43;
wire	SYNTHESIZED_WIRE_44;





CMP16	b2v_inst(
	.A(A[15:0]),
	.B(B[15:0]),
	.G(SYNTHESIZED_WIRE_0),
	.E(SYNTHESIZED_WIRE_1),
	.L(SYNTHESIZED_WIRE_2));


CMP1	b2v_inst1(
	.A(A[16]),
	.B(B[16]),
	.Gi_1(SYNTHESIZED_WIRE_0),
	.Ei_1(SYNTHESIZED_WIRE_1),
	.Li_1(SYNTHESIZED_WIRE_2),
	.G(SYNTHESIZED_WIRE_24),
	.E(SYNTHESIZED_WIRE_25),
	.L(SYNTHESIZED_WIRE_26));


CMP1	b2v_inst10(
	.A(A[25]),
	.B(B[25]),
	.Gi_1(SYNTHESIZED_WIRE_3),
	.Ei_1(SYNTHESIZED_WIRE_4),
	.Li_1(SYNTHESIZED_WIRE_5),
	.G(SYNTHESIZED_WIRE_6),
	.E(SYNTHESIZED_WIRE_7),
	.L(SYNTHESIZED_WIRE_8));


CMP1	b2v_inst11(
	.A(A[26]),
	.B(B[26]),
	.Gi_1(SYNTHESIZED_WIRE_6),
	.Ei_1(SYNTHESIZED_WIRE_7),
	.Li_1(SYNTHESIZED_WIRE_8),
	.G(SYNTHESIZED_WIRE_9),
	.E(SYNTHESIZED_WIRE_10),
	.L(SYNTHESIZED_WIRE_11));


CMP1	b2v_inst12(
	.A(A[27]),
	.B(B[27]),
	.Gi_1(SYNTHESIZED_WIRE_9),
	.Ei_1(SYNTHESIZED_WIRE_10),
	.Li_1(SYNTHESIZED_WIRE_11),
	.G(SYNTHESIZED_WIRE_12),
	.E(SYNTHESIZED_WIRE_13),
	.L(SYNTHESIZED_WIRE_14));


CMP1	b2v_inst13(
	.A(A[28]),
	.B(B[28]),
	.Gi_1(SYNTHESIZED_WIRE_12),
	.Ei_1(SYNTHESIZED_WIRE_13),
	.Li_1(SYNTHESIZED_WIRE_14),
	.G(SYNTHESIZED_WIRE_15),
	.E(SYNTHESIZED_WIRE_16),
	.L(SYNTHESIZED_WIRE_17));


CMP1	b2v_inst14(
	.A(A[29]),
	.B(B[29]),
	.Gi_1(SYNTHESIZED_WIRE_15),
	.Ei_1(SYNTHESIZED_WIRE_16),
	.Li_1(SYNTHESIZED_WIRE_17),
	.G(SYNTHESIZED_WIRE_18),
	.E(SYNTHESIZED_WIRE_19),
	.L(SYNTHESIZED_WIRE_20));


CMP1	b2v_inst15(
	.A(A[30]),
	.B(B[30]),
	.Gi_1(SYNTHESIZED_WIRE_18),
	.Ei_1(SYNTHESIZED_WIRE_19),
	.Li_1(SYNTHESIZED_WIRE_20),
	.G(SYNTHESIZED_WIRE_21),
	.E(SYNTHESIZED_WIRE_22),
	.L(SYNTHESIZED_WIRE_23));


CMP1	b2v_inst16(
	.A(A[31]),
	.B(B[31]),
	.Gi_1(SYNTHESIZED_WIRE_21),
	.Ei_1(SYNTHESIZED_WIRE_22),
	.Li_1(SYNTHESIZED_WIRE_23),
	.G(G),
	.E(E),
	.L(L));


CMP1	b2v_inst2(
	.A(A[17]),
	.B(B[17]),
	.Gi_1(SYNTHESIZED_WIRE_24),
	.Ei_1(SYNTHESIZED_WIRE_25),
	.Li_1(SYNTHESIZED_WIRE_26),
	.G(SYNTHESIZED_WIRE_27),
	.E(SYNTHESIZED_WIRE_28),
	.L(SYNTHESIZED_WIRE_29));


CMP1	b2v_inst3(
	.A(A[18]),
	.B(B[18]),
	.Gi_1(SYNTHESIZED_WIRE_27),
	.Ei_1(SYNTHESIZED_WIRE_28),
	.Li_1(SYNTHESIZED_WIRE_29),
	.G(SYNTHESIZED_WIRE_30),
	.E(SYNTHESIZED_WIRE_31),
	.L(SYNTHESIZED_WIRE_32));


CMP1	b2v_inst4(
	.A(A[19]),
	.B(B[19]),
	.Gi_1(SYNTHESIZED_WIRE_30),
	.Ei_1(SYNTHESIZED_WIRE_31),
	.Li_1(SYNTHESIZED_WIRE_32),
	.G(SYNTHESIZED_WIRE_33),
	.E(SYNTHESIZED_WIRE_34),
	.L(SYNTHESIZED_WIRE_35));


CMP1	b2v_inst5(
	.A(A[20]),
	.B(B[20]),
	.Gi_1(SYNTHESIZED_WIRE_33),
	.Ei_1(SYNTHESIZED_WIRE_34),
	.Li_1(SYNTHESIZED_WIRE_35),
	.G(SYNTHESIZED_WIRE_36),
	.E(SYNTHESIZED_WIRE_37),
	.L(SYNTHESIZED_WIRE_38));


CMP1	b2v_inst6(
	.A(A[21]),
	.B(B[21]),
	.Gi_1(SYNTHESIZED_WIRE_36),
	.Ei_1(SYNTHESIZED_WIRE_37),
	.Li_1(SYNTHESIZED_WIRE_38),
	.G(SYNTHESIZED_WIRE_39),
	.E(SYNTHESIZED_WIRE_40),
	.L(SYNTHESIZED_WIRE_41));


CMP1	b2v_inst7(
	.A(A[22]),
	.B(B[22]),
	.Gi_1(SYNTHESIZED_WIRE_39),
	.Ei_1(SYNTHESIZED_WIRE_40),
	.Li_1(SYNTHESIZED_WIRE_41),
	.G(SYNTHESIZED_WIRE_42),
	.E(SYNTHESIZED_WIRE_43),
	.L(SYNTHESIZED_WIRE_44));


CMP1	b2v_inst8(
	.A(A[23]),
	.B(B[23]),
	.Gi_1(SYNTHESIZED_WIRE_42),
	.Ei_1(SYNTHESIZED_WIRE_43),
	.Li_1(SYNTHESIZED_WIRE_44),
	.G(G_ALTERA_SYNTHESIZED),
	.E(E_ALTERA_SYNTHESIZED),
	.L(L_ALTERA_SYNTHESIZED));


CMP1	b2v_inst9(
	.A(A[24]),
	.B(B[24]),
	.Gi_1(G_ALTERA_SYNTHESIZED),
	.Ei_1(E_ALTERA_SYNTHESIZED),
	.Li_1(L_ALTERA_SYNTHESIZED),
	.G(SYNTHESIZED_WIRE_3),
	.E(SYNTHESIZED_WIRE_4),
	.L(SYNTHESIZED_WIRE_5));


endmodule
