// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Thu Aug 13 12:40:18 2026

Riscv32i Riscv32i_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RESET(RESET_sig) ,	// input  RESET_sig
	.N(N_sig) ,	// output  N_sig
	.Z(Z_sig) ,	// output  Z_sig
	.RESULT(RESULT_sig) 	// output [31:0] RESULT_sig
);

