// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.

// PROGRAM		"Quartus II 64-Bit"
// VERSION		"Version 13.1.0 Build 162 10/23/2013 SJ Web Edition"
// CREATED		"Wed Sep 02 19:28:24 2026"

module sdram_controller(
	CLK,
	CS,
	RD,
	WR,
	RESET,
	ADDR,
	DATA_IN,
	CKE,
	CS_N,
	RAS_N,
	CAS_N,
	WE_N,
	DQML,
	DQMH,
	ACCESS_DONE,
	A,
	BA,
	DATA_OUT,
	DQ
);


input wire	CLK;
input wire	CS;
input wire	RD;
input wire	WR;
input wire	RESET;
input wire	[24:0] ADDR;
input wire	[15:0] DATA_IN;
output wire	CKE;
output wire	CS_N;
output wire	RAS_N;
output wire	CAS_N;
output wire	WE_N;
output wire	DQML;
output wire	DQMH;
output wire	ACCESS_DONE;
output wire	[12:0] A;
output wire	[1:0] BA;
output wire	[15:0] DATA_OUT;
inout wire	[15:0] DQ;

wire	ACCESS_ACTIVE;
wire	[24:0] ACCESS_ADDR;
wire	[15:0] ACCESS_DATA_IN;
wire	[15:0] CMD;
wire	DQM_ENABLE;
wire	INIT_DONE;
wire	INIT_RC_DONE;
wire	INIT_REFRESH_8_DONE;
wire	INIT_REFRESH_FINISHED;
wire	INTERNAL_COMMAND;
wire	INVALID_ACCESS;
wire	jedan;
wire	MORE_INIT_REFRESH;
wire	nula;
wire	[15:0] nula16bitna;
wire	PRECHARGE_START;
wire	RC_DONE;
wire	READ;
wire	REFRESH_ACTIVE;
wire	REFRESH_DUE;
wire	REQUEST_READ;
wire	REQUEST_WRITE;
wire	SDRAM_INIT_DONE;
wire	START_ACCESS;
wire	STATE_ACTIVE;
wire	STATE_INIT;
wire	STATE_INIT_REFRESH;
wire	STATE_INIT_WAIT_MRD_1;
wire	STATE_INIT_WAIT_MRD_2;
wire	STATE_INIT_WAIT_RC;
wire	STATE_INIT_WAIT_RP;
wire	STATE_MRS;
wire	STATE_PALL;
wire	STATE_PRECHARGE;
wire	STATE_PRECHARGE_WAIT;
wire	STATE_READ;
wire	STATE_READ_WAIT_1;
wire	STATE_READ_WAIT_2;
wire	STATE_READ_WAIT_3;
wire	STATE_READY;
wire	STATE_REFRESH;
wire	STATE_REFRESH_PALL;
wire	STATE_REFRESH_WAIT_RC;
wire	STATE_REFRESH_WAIT_RP;
wire	STATE_WAIT_RCD;
wire	STATE_WRITE;
wire	STATE_WRITE_WAIT;
wire	WRITE;
wire	SYNTHESIZED_WIRE_0;
wire	[15:0] SYNTHESIZED_WIRE_1;
wire	[15:0] SYNTHESIZED_WIRE_2;
wire	SYNTHESIZED_WIRE_3;
wire	SYNTHESIZED_WIRE_4;
wire	SYNTHESIZED_WIRE_5;
wire	SYNTHESIZED_WIRE_6;
wire	SYNTHESIZED_WIRE_7;
wire	SYNTHESIZED_WIRE_8;
wire	SYNTHESIZED_WIRE_9;
wire	SYNTHESIZED_WIRE_10;
wire	SYNTHESIZED_WIRE_11;
wire	SYNTHESIZED_WIRE_12;
wire	SYNTHESIZED_WIRE_13;
wire	SYNTHESIZED_WIRE_14;
wire	SYNTHESIZED_WIRE_15;
wire	SYNTHESIZED_WIRE_16;
wire	SYNTHESIZED_WIRE_17;
wire	SYNTHESIZED_WIRE_18;
wire	SYNTHESIZED_WIRE_19;
wire	[15:0] SYNTHESIZED_WIRE_20;
wire	[15:0] SYNTHESIZED_WIRE_21;
wire	SYNTHESIZED_WIRE_22;
wire	[15:0] SYNTHESIZED_WIRE_23;
wire	[15:0] SYNTHESIZED_WIRE_24;
wire	SYNTHESIZED_WIRE_25;
wire	[15:0] SYNTHESIZED_WIRE_26;
wire	[15:0] SYNTHESIZED_WIRE_27;
wire	SYNTHESIZED_WIRE_28;
wire	[15:0] SYNTHESIZED_WIRE_29;
wire	[15:0] SYNTHESIZED_WIRE_30;
wire	SYNTHESIZED_WIRE_31;
wire	[15:0] SYNTHESIZED_WIRE_32;
wire	[15:0] SYNTHESIZED_WIRE_33;
wire	SYNTHESIZED_WIRE_34;
wire	[15:0] SYNTHESIZED_WIRE_35;
wire	[15:0] SYNTHESIZED_WIRE_36;
wire	SYNTHESIZED_WIRE_37;
wire	SYNTHESIZED_WIRE_38;
wire	[15:0] SYNTHESIZED_WIRE_39;
wire	[15:0] SYNTHESIZED_WIRE_40;
wire	SYNTHESIZED_WIRE_41;
wire	SYNTHESIZED_WIRE_42;
wire	SYNTHESIZED_WIRE_43;
wire	SYNTHESIZED_WIRE_44;
wire	[12:0] SYNTHESIZED_WIRE_45;
wire	[12:0] SYNTHESIZED_WIRE_46;
wire	SYNTHESIZED_WIRE_47;
wire	[1:0] SYNTHESIZED_WIRE_48;
wire	SYNTHESIZED_WIRE_49;
wire	SYNTHESIZED_WIRE_50;
wire	[15:0] SYNTHESIZED_WIRE_51;
wire	[15:0] SYNTHESIZED_WIRE_52;
wire	[15:0] SYNTHESIZED_WIRE_53;
wire	[15:0] SYNTHESIZED_WIRE_54;
wire	SYNTHESIZED_WIRE_55;
wire	SYNTHESIZED_WIRE_56;
wire	SYNTHESIZED_WIRE_57;
wire	SYNTHESIZED_WIRE_58;
wire	SYNTHESIZED_WIRE_59;
wire	SYNTHESIZED_WIRE_60;
wire	[15:0] SYNTHESIZED_WIRE_61;
wire	[15:0] SYNTHESIZED_WIRE_62;
wire	[15:0] SYNTHESIZED_WIRE_63;
wire	[15:0] SYNTHESIZED_WIRE_64;
wire	SYNTHESIZED_WIRE_65;
wire	[12:0] SYNTHESIZED_WIRE_66;
wire	SYNTHESIZED_WIRE_67;
wire	SYNTHESIZED_WIRE_68;
wire	SYNTHESIZED_WIRE_69;

assign	DQML = SYNTHESIZED_WIRE_69;
assign	DQMH = SYNTHESIZED_WIRE_69;
wire	[1:0] GDFX_TEMP_SIGNAL_1;
wire	[12:0] GDFX_TEMP_SIGNAL_2;
wire	[12:0] GDFX_TEMP_SIGNAL_0;


assign	GDFX_TEMP_SIGNAL_1 = {nula,nula};
assign	GDFX_TEMP_SIGNAL_2 = {nula,nula,nula,ACCESS_ADDR[9:0]};
assign	GDFX_TEMP_SIGNAL_0 = {nula,nula,CMD[3],nula,nula,nula,nula,nula,nula,nula,nula,nula,nula};


REG16_LD_CL_INC_DEC	b2v_inst(
	.LD(nula),
	.C0(jedan),
	.INC(jedan),
	.E0(nula),
	.DEC(nula),
	.CL(SYNTHESIZED_WIRE_0),
	.clk(CLK),
	.I(nula16bitna),
	
	
	.A(SYNTHESIZED_WIRE_23));


CONST_10000_16b	b2v_inst1(
	.result(SYNTHESIZED_WIRE_24));

assign	WRITE = WR & CS;

assign	PRECHARGE_START = STATE_WRITE_WAIT | STATE_READ_WAIT_3;


REG1_LD_CL	b2v_inst101(
	.LD(jedan),
	.I(PRECHARGE_START),
	.CL(RESET),
	.clk(CLK),
	.A(STATE_PRECHARGE));


MPX2_16BIT	b2v_inst102(
	.S(STATE_PRECHARGE),
	.E(jedan),
	.I0(SYNTHESIZED_WIRE_1),
	.I1(SYNTHESIZED_WIRE_2),
	.D(CMD));


CONST_CMD_PRE_16b	b2v_inst103(
	.result(SYNTHESIZED_WIRE_2));


REG1_LD_CL	b2v_inst104(
	.LD(jedan),
	.I(STATE_PRECHARGE),
	.CL(RESET),
	.clk(CLK),
	.A(STATE_PRECHARGE_WAIT));

assign	SYNTHESIZED_WIRE_47 = STATE_ACTIVE | STATE_WRITE | STATE_PRECHARGE | STATE_READ;

assign	STATE_READY = SDRAM_INIT_DONE & SYNTHESIZED_WIRE_3 & SYNTHESIZED_WIRE_4;

assign	SYNTHESIZED_WIRE_4 =  ~ACCESS_ACTIVE;


REG1_LD_CL	b2v_inst108(
	.LD(START_ACCESS),
	.I(jedan),
	.CL(SYNTHESIZED_WIRE_5),
	.clk(CLK),
	.A(ACCESS_ACTIVE));

assign	SYNTHESIZED_WIRE_5 = STATE_PRECHARGE_WAIT | RESET;

assign	READ = CS & RD;

assign	SYNTHESIZED_WIRE_69 =  ~DQM_ENABLE;

assign	SYNTHESIZED_WIRE_50 = WRITE | READ;

assign	SYNTHESIZED_WIRE_56 = STATE_PRECHARGE_WAIT | RESET;

assign	SYNTHESIZED_WIRE_58 = STATE_PRECHARGE_WAIT | RESET;

assign	SYNTHESIZED_WIRE_8 = INIT_RC_DONE | RESET;

assign	SYNTHESIZED_WIRE_28 = STATE_REFRESH_PALL | STATE_PALL;

assign	SYNTHESIZED_WIRE_7 = STATE_READ_WAIT_2 | STATE_READ_WAIT_3 | STATE_READ_WAIT_1;

assign	SYNTHESIZED_WIRE_6 = STATE_WRITE | STATE_READ;

assign	DQM_ENABLE = SYNTHESIZED_WIRE_6 | SYNTHESIZED_WIRE_7;


REG1_LD_CL	b2v_inst119(
	.LD(STATE_INIT_REFRESH),
	.I(jedan),
	.CL(SYNTHESIZED_WIRE_8),
	.clk(CLK),
	.A(STATE_INIT_WAIT_RC));

assign	SYNTHESIZED_WIRE_16 = STATE_REFRESH_PALL | RESET;

assign	SYNTHESIZED_WIRE_31 = STATE_REFRESH | STATE_INIT_REFRESH;

assign	SYNTHESIZED_WIRE_38 = INIT_REFRESH_8_DONE | RESET;


REG1_LD_CL	b2v_inst122(
	.LD(INIT_REFRESH_8_DONE),
	.I(jedan),
	.CL(RESET),
	.clk(CLK),
	.A(INIT_REFRESH_FINISHED));

assign	MORE_INIT_REFRESH = SYNTHESIZED_WIRE_9 & INIT_RC_DONE & SYNTHESIZED_WIRE_10;

assign	SYNTHESIZED_WIRE_9 =  ~INIT_REFRESH_FINISHED;

assign	SYNTHESIZED_WIRE_43 = INIT_REFRESH_FINISHED & INIT_RC_DONE;

assign	SYNTHESIZED_WIRE_13 = INTERNAL_COMMAND | CS;

assign	INTERNAL_COMMAND = STATE_PALL | STATE_MRS | REFRESH_ACTIVE | STATE_INIT_REFRESH;

assign	SYNTHESIZED_WIRE_67 = SYNTHESIZED_WIRE_11 & SYNTHESIZED_WIRE_12 & SDRAM_INIT_DONE;

assign	SYNTHESIZED_WIRE_12 =  ~REFRESH_DUE;

assign	CS_N =  ~SYNTHESIZED_WIRE_13;


REG1_LD_CL	b2v_inst14(
	.LD(RESET),
	.I(jedan),
	.CL(INIT_DONE),
	.clk(CLK)
	);


REG1_LD_CL	b2v_inst15(
	.LD(INIT_DONE),
	.I(jedan),
	.CL(SYNTHESIZED_WIRE_14),
	.clk(CLK),
	.A(STATE_PALL));


REG1_LD_CL	b2v_inst16(
	.LD(SYNTHESIZED_WIRE_15),
	.I(jedan),
	.CL(SYNTHESIZED_WIRE_16),
	.clk(CLK),
	.A(STATE_REFRESH_PALL));


REG1_LD_CL	b2v_inst18(
	.LD(STATE_REFRESH_PALL),
	.I(jedan),
	.CL(SYNTHESIZED_WIRE_17),
	.clk(CLK),
	.A(STATE_REFRESH_WAIT_RP));


REG1_LD_CL	b2v_inst19(
	.LD(STATE_REFRESH_WAIT_RP),
	.I(jedan),
	.CL(SYNTHESIZED_WIRE_18),
	.clk(CLK),
	.A(STATE_REFRESH));


CONST_0_16b	b2v_inst2(
	.result(nula16bitna));

assign	SYNTHESIZED_WIRE_17 = STATE_REFRESH_WAIT_RP | RESET;

assign	SYNTHESIZED_WIRE_18 = STATE_REFRESH | RESET;


REG16_LD_CL_INC_DEC	b2v_inst22(
	.LD(nula),
	.C0(jedan),
	.INC(STATE_REFRESH_WAIT_RC),
	.E0(nula),
	.DEC(nula),
	.CL(SYNTHESIZED_WIRE_19),
	.clk(CLK),
	.I(nula16bitna),
	
	
	.A(SYNTHESIZED_WIRE_20));

assign	SYNTHESIZED_WIRE_19 = RC_DONE | RESET;


CMP16	b2v_inst24(
	.A(SYNTHESIZED_WIRE_20),
	.B(SYNTHESIZED_WIRE_21),
	
	.E(RC_DONE)
	);


REG1_LD_CL	b2v_inst25(
	.LD(STATE_REFRESH),
	.I(jedan),
	.CL(SYNTHESIZED_WIRE_22),
	.clk(CLK),
	.A(STATE_REFRESH_WAIT_RC));

assign	SYNTHESIZED_WIRE_22 = RC_DONE | RESET;

assign	SYNTHESIZED_WIRE_68 = RC_DONE | RESET;

assign	REFRESH_ACTIVE = STATE_REFRESH_PALL | STATE_REFRESH | STATE_REFRESH_WAIT_RC | STATE_REFRESH_WAIT_RP;


CONST_389_16b	b2v_inst29(
	.result(SYNTHESIZED_WIRE_52));


CMP16	b2v_inst3(
	.A(SYNTHESIZED_WIRE_23),
	.B(SYNTHESIZED_WIRE_24),
	
	.E(INIT_DONE)
	);


CONST_3_16b	b2v_inst30(
	.result(SYNTHESIZED_WIRE_27));


REG16_LD_CL_INC_DEC	b2v_inst31(
	.LD(nula),
	.C0(jedan),
	.INC(STATE_INIT_WAIT_RC),
	.E0(nula),
	.DEC(nula),
	.CL(SYNTHESIZED_WIRE_25),
	.clk(CLK),
	.I(nula16bitna),
	
	
	.A(SYNTHESIZED_WIRE_26));

assign	SYNTHESIZED_WIRE_25 = INIT_RC_DONE | RESET;


CMP16	b2v_inst33(
	.A(SYNTHESIZED_WIRE_26),
	.B(SYNTHESIZED_WIRE_27),
	
	.E(INIT_RC_DONE)
	);


CONST_CMD_NOP_16b	b2v_inst34(
	.result(SYNTHESIZED_WIRE_29));


CONST_CMD_PALL_16b	b2v_inst35(
	.result(SYNTHESIZED_WIRE_30));


CONST_CMD_REFRESH_16b	b2v_inst36(
	.result(SYNTHESIZED_WIRE_33));


MPX2_16BIT	b2v_inst37(
	.S(SYNTHESIZED_WIRE_28),
	.E(jedan),
	.I0(SYNTHESIZED_WIRE_29),
	.I1(SYNTHESIZED_WIRE_30),
	.D(SYNTHESIZED_WIRE_32));


MPX2_16BIT	b2v_inst38(
	.S(SYNTHESIZED_WIRE_31),
	.E(jedan),
	.I0(SYNTHESIZED_WIRE_32),
	.I1(SYNTHESIZED_WIRE_33),
	.D(SYNTHESIZED_WIRE_35));


REG16_LD_CL	b2v_inst39(
	.LD(SYNTHESIZED_WIRE_34),
	.CL(RESET),
	.clk(CLK),
	.I(DATA_IN),
	.A(ACCESS_DATA_IN));

assign	SYNTHESIZED_WIRE_0 = INIT_DONE | RESET;

assign	SYNTHESIZED_WIRE_11 =  ~REFRESH_ACTIVE;


CONST_8_16b	b2v_inst41(
	.result(SYNTHESIZED_WIRE_40));


MPX2_16BIT	b2v_inst42(
	.S(STATE_MRS),
	.E(jedan),
	.I0(SYNTHESIZED_WIRE_35),
	.I1(SYNTHESIZED_WIRE_36),
	.D(SYNTHESIZED_WIRE_53));


REG1_LD_CL	b2v_inst43(
	.LD(STATE_PALL),
	.I(jedan),
	.CL(SYNTHESIZED_WIRE_37),
	.clk(CLK),
	.A(STATE_INIT_WAIT_RP));

assign	SYNTHESIZED_WIRE_37 = STATE_INIT_WAIT_RP | RESET;


REG16_LD_CL_INC_DEC	b2v_inst47(
	.LD(nula),
	.C0(jedan),
	.INC(STATE_INIT_REFRESH),
	.E0(nula),
	.DEC(nula),
	.CL(SYNTHESIZED_WIRE_38),
	.clk(CLK),
	.I(nula16bitna),
	
	
	.A(SYNTHESIZED_WIRE_39));


CMP16	b2v_inst48(
	.A(SYNTHESIZED_WIRE_39),
	.B(SYNTHESIZED_WIRE_40),
	
	.E(INIT_REFRESH_8_DONE)
	);

assign	SYNTHESIZED_WIRE_10 =  ~INIT_REFRESH_8_DONE;


REG1_LD_CL	b2v_inst51(
	.LD(SYNTHESIZED_WIRE_41),
	.I(jedan),
	.CL(SYNTHESIZED_WIRE_42),
	.clk(CLK),
	.A(STATE_INIT_REFRESH));

assign	SYNTHESIZED_WIRE_42 = STATE_INIT_REFRESH | RESET;


REG1_LD_CL	b2v_inst53(
	.LD(SYNTHESIZED_WIRE_43),
	.I(jedan),
	.CL(SYNTHESIZED_WIRE_44),
	.clk(CLK),
	.A(STATE_MRS));


assign	SYNTHESIZED_WIRE_44 = STATE_MRS | RESET;

assign	SYNTHESIZED_WIRE_41 = MORE_INIT_REFRESH | STATE_INIT_WAIT_RP;


CONST_CMD_MRS_16b	b2v_inst57(
	.result(SYNTHESIZED_WIRE_36));


MPX2_13BIT	b2v_inst58(
	.S(STATE_MRS),
	.E(jedan),
	.I0(GDFX_TEMP_SIGNAL_0),
	.I1(SYNTHESIZED_WIRE_45),
	.D(SYNTHESIZED_WIRE_46));


CONST_MODE_030_13b	b2v_inst59(
	.result(SYNTHESIZED_WIRE_45));


REG25_LD_CL	b2v_inst6(
	.LD(START_ACCESS),
	.CL(RESET),
	.CLK(CLK),
	.I(ADDR),
	.A(ACCESS_ADDR));


MPX2_2BIT	b2v_inst60(
	.S(STATE_MRS),
	.E(jedan),
	.I0(CMD[5:4]),
	.I1(GDFX_TEMP_SIGNAL_1),
	.D(SYNTHESIZED_WIRE_48));


REG1_LD_CL	b2v_inst61(
	.LD(jedan),
	.I(STATE_MRS),
	.CL(RESET),
	.clk(CLK),
	.A(STATE_INIT_WAIT_MRD_1));


REG1_LD_CL	b2v_inst62(
	.LD(jedan),
	.I(STATE_INIT_WAIT_MRD_1),
	.CL(RESET),
	.clk(CLK),
	.A(STATE_INIT_WAIT_MRD_2));


REG1_LD_CL	b2v_inst63(
	.LD(STATE_INIT_WAIT_MRD_2),
	.I(jedan),
	.CL(RESET),
	.clk(CLK),
	.A(SDRAM_INIT_DONE));

assign	SYNTHESIZED_WIRE_34 = WRITE & START_ACCESS;

assign	SYNTHESIZED_WIRE_3 =  ~REFRESH_ACTIVE;


MPX2_13BIT	b2v_inst66(
	.S(STATE_ACTIVE),
	.E(jedan),
	.I0(SYNTHESIZED_WIRE_46),
	.I1(ACCESS_ADDR[22:10]),
	.D(SYNTHESIZED_WIRE_66));


MPX2_2BIT	b2v_inst67(
	.S(SYNTHESIZED_WIRE_47),
	.E(jedan),
	.I0(SYNTHESIZED_WIRE_48),
	.I1(ACCESS_ADDR[24:23]),
	.D(BA));

assign	START_ACCESS = STATE_READY & SYNTHESIZED_WIRE_49 & SYNTHESIZED_WIRE_50;


CMP16	b2v_inst7(
	.A(SYNTHESIZED_WIRE_51),
	.B(SYNTHESIZED_WIRE_52),
	
	.E(REFRESH_DUE)
	);

assign	SYNTHESIZED_WIRE_49 =  ~REFRESH_DUE;


REG1_LD_CL	b2v_inst72(
	.LD(jedan),
	.I(START_ACCESS),
	.CL(RESET),
	.clk(CLK),
	.A(STATE_ACTIVE));


MPX2_16BIT	b2v_inst73(
	.S(STATE_ACTIVE),
	.E(jedan),
	.I0(SYNTHESIZED_WIRE_53),
	.I1(SYNTHESIZED_WIRE_54),
	.D(SYNTHESIZED_WIRE_61));


CONST_CMD_ACTIVE_16b	b2v_inst74(
	.result(SYNTHESIZED_WIRE_54));


REG1_LD_CL	b2v_inst75(
	.LD(jedan),
	.I(STATE_ACTIVE),
	.CL(RESET),
	.clk(CLK),
	.A(STATE_WAIT_RCD));


CONST_3_16b	b2v_inst76(
	.result(SYNTHESIZED_WIRE_21));


REG1_LD_CL	b2v_inst77(
	.LD(SYNTHESIZED_WIRE_55),
	.I(jedan),
	.CL(SYNTHESIZED_WIRE_56),
	.clk(CLK),
	.A(REQUEST_READ));

assign	SYNTHESIZED_WIRE_55 = START_ACCESS & READ;


REG1_LD_CL	b2v_inst79(
	.LD(SYNTHESIZED_WIRE_57),
	.I(jedan),
	.CL(SYNTHESIZED_WIRE_58),
	.clk(CLK),
	.A(REQUEST_WRITE));


assign	SYNTHESIZED_WIRE_57 = START_ACCESS & WRITE;

assign	SYNTHESIZED_WIRE_59 = STATE_WAIT_RCD & REQUEST_READ;


REG1_LD_CL	b2v_inst82(
	.LD(jedan),
	.I(SYNTHESIZED_WIRE_59),
	.CL(RESET),
	.clk(CLK),
	.A(STATE_READ));

assign	SYNTHESIZED_WIRE_60 = STATE_WAIT_RCD & REQUEST_WRITE;


REG1_LD_CL	b2v_inst84(
	.LD(jedan),
	.I(SYNTHESIZED_WIRE_60),
	.CL(RESET),
	.clk(CLK),
	.A(STATE_WRITE));


MPX2_16BIT	b2v_inst85(
	.S(STATE_READ),
	.E(jedan),
	.I0(SYNTHESIZED_WIRE_61),
	.I1(SYNTHESIZED_WIRE_62),
	.D(SYNTHESIZED_WIRE_63));


CONST_CMD_READ_16b	b2v_inst86(
	.result(SYNTHESIZED_WIRE_62));


MPX2_16BIT	b2v_inst87(
	.S(STATE_WRITE),
	.E(jedan),
	.I0(SYNTHESIZED_WIRE_63),
	.I1(SYNTHESIZED_WIRE_64),
	.D(SYNTHESIZED_WIRE_1));


CONST_CMD_WRITE_16b	b2v_inst88(
	.result(SYNTHESIZED_WIRE_64));


MPX2_13BIT	b2v_inst89(
	.S(SYNTHESIZED_WIRE_65),
	.E(jedan),
	.I0(SYNTHESIZED_WIRE_66),
	.I1(GDFX_TEMP_SIGNAL_2),
	.D(A));


assign	SYNTHESIZED_WIRE_65 = STATE_WRITE | STATE_READ;

assign	SYNTHESIZED_WIRE_15 = REFRESH_DUE & STATE_READY;

assign	SYNTHESIZED_WIRE_14 = STATE_PALL | RESET;


REG1_LD_CL	b2v_inst93(
	.LD(jedan),
	.I(STATE_WRITE),
	.CL(RESET),
	.clk(CLK),
	.A(STATE_WRITE_WAIT));


TRI_16b	b2v_inst95(
	.BOOL(STATE_WRITE),
	.IN(ACCESS_DATA_IN),
	.OUT(DQ));


REG1_LD_CL	b2v_inst96(
	.LD(jedan),
	.I(STATE_READ),
	.CL(RESET),
	.clk(CLK),
	.A(STATE_READ_WAIT_1));


REG1_LD_CL	b2v_inst97(
	.LD(jedan),
	.I(STATE_READ_WAIT_1),
	.CL(RESET),
	.clk(CLK),
	.A(STATE_READ_WAIT_2));


REG1_LD_CL	b2v_inst98(
	.LD(jedan),
	.I(STATE_READ_WAIT_2),
	.CL(RESET),
	.clk(CLK),
	.A(STATE_READ_WAIT_3));


REG16_LD_CL	b2v_inst99(
	.LD(STATE_READ_WAIT_3),
	.CL(RESET),
	.clk(CLK),
	.I(DQ),
	.A(DATA_OUT));


REG16_LD_CL_INC_DEC	b2v_REFRESH_COUNTER(
	.LD(nula),
	.C0(jedan),
	.INC(SYNTHESIZED_WIRE_67),
	.E0(nula),
	.DEC(nula),
	.CL(SYNTHESIZED_WIRE_68),
	.clk(CLK),
	.I(nula16bitna),
	
	
	.A(SYNTHESIZED_WIRE_51));

assign	CKE = jedan;
assign	RAS_N = CMD[8];
assign	CAS_N = CMD[7];
assign	WE_N = CMD[6];
assign	ACCESS_DONE = STATE_PRECHARGE_WAIT;
assign	jedan = 1;
assign	nula = 0;

endmodule
